base:
  project: MLOps

raw_data:
  data_src: data_source

load_data:
  num_classes: 2
  row_data: data_source
  preprocessed_data: data/processed
  full_path: dlproject/data_source

train:
  split_ratio: 0.80

model:
  name: VGG16
  input_shape: [225, 225, 3]
  num_classes: 2
  trainable: True  
  train_path: data/processed/train
  test_path: data/processed/test
  optimizer: adam
  loss: binary_crossentropy  
  metrics: ["accuracy"]
  epochs: 1
  
   
  batch_size : 32
  image_size : [225, 225]
  save_dir : models/trained31.h5
  learning_rate: 0.00001  


img_augment:
  rescale: 0.00392156862745098
  shear_range: 0.3
  zoom_range: 0.3
  horizontal_flip: True
  vertical_flip: True
  rotation_range: 30
  width_shift_range: 0.2
  height_shift_range: 0.2
  brightness_range: [0.8, 1.2]
  batch_size: 32
  class_mode: 'binary'

model_dir: models

mlflow_config:
  artifact_dir: artifacts
  experiment_name: Violence_detection
  run_name: mlops
  registered_model_name: Violence_detection
  remote_server_uri: http://127.0.0.1:5000
